name: business
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.0.4
  built_collection: ^5.0.0
  equatable: ^2.0.2
  dartz: ^0.10.0-nullsafety.2
  flutter_redux: ^0.8.2
  mockito: ^5.0.8
  redux: ^5.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  built_value_generator: ^8.0.4
  test: ^1.16.5
  build_runner: ^2.0.3
