class ExpensesTriggers {
  static const save_history_after_update_expense = 'CREATE TRIGGER '
      'save_history_after_update_expense '
      'BEFORE UPDATE ON expenses '
      'BEGIN '
      ' INSERT INTO expenses_history('
      '   expense_id,'
      '   description,'
      '   value,'
      '   date,'
      '   payment_method_id,'
      '   subcategory_id,'
      '   store_id,'
      '   altered_at'
      ' ) '
      ' values('
      '   old.id,'
      '   old.description,'
      '   old.value,'
      '   old.date,'
      '   old.payment_method_id,'
      '   old.subcategory_id,'
      '   old.store_id,'
      '   old.updated_at'
      ' );'
      'END;';

  static const save_history_after_delete_expense = 'CREATE TRIGGER '
      'save_history_after_delete_expense '
      'BEFORE DELETE ON expenses '
      'BEGIN '
      ' INSERT INTO expenses_history('
      '   expense_id,'
      '   description,'
      '   value,'
      '   date,'
      '   payment_method_id,'
      '   subcategory_id,'
      '   store_id,'
      '   altered_at'
      ' ) '
      ' values('
      '   old.id,'
      '   old.description,'
      '   old.value,'
      '   old.date,'
      '   old.payment_method_id,'
      '   old.subcategory_id,'
      '   old.store_id,'
      '   old.updated_at'
      ' );'
      'END;';
}
