name: infrastructure
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  moor: ^3.4.0

dev_dependencies:
  sqflite_common_ffi: ^1.1.1+3
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.11.1
  moor_generator: ^3.4.1
