import 'package:flutter/material.dart';

class ColorService {
  static final colors = {
    Colors.red: 'red',
    Colors.pink: 'pink',
    Colors.purple: 'purple',
    Colors.deepPurple: 'deepPurple',
    Colors.indigo: 'indigo',
    Colors.blue: 'blue',
    Colors.lightBlue: 'lightBlue',
    Colors.cyan: 'cyan',
    Colors.teal: 'teal',
    Colors.green: 'green',
    Colors.lightGreen: 'lightGreen',
    Colors.lime: 'lime',
    Colors.yellow: 'yellow',
    Colors.amber: 'amber',
    Colors.orange: 'orange',
    Colors.deepOrange: 'deepOrange',
    Colors.brown: 'brown',
    Colors.grey: 'grey',
    Colors.blueGrey: 'blueGrey',
    Colors.redAccent: 'redAccent',
    Colors.pinkAccent: 'pinkAccent',
    Colors.purpleAccent: 'purpleAccent',
    Colors.deepPurpleAccent: 'deepPurpleAccent',
    Colors.indigoAccent: 'indigoAccent',
    Colors.blueAccent: 'blueAccent',
    Colors.lightBlueAccent: 'lightBlueAccent',
    Colors.cyanAccent: 'cyanAccent',
    Colors.tealAccent: 'tealAccent',
    Colors.greenAccent: 'greenAccent',
    Colors.lightGreenAccent: 'lightGreenAccent',
    Colors.limeAccent: 'limeAccent',
    Colors.yellowAccent: 'yellowAccent',
    Colors.amberAccent: 'amberAccent',
    Colors.orangeAccent: 'orangeAccent',
    Colors.deepOrangeAccent: 'deepOrangeAccent',
  };
}
