# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.4'

      - name: Install dependencies in infrastructure
        run: cd infrastructure && flutter pub get

      - name: Generate dart files in infrastructure 
        run: cd infrastructure && flutter pub run build_runner build

      - name: Analyze project source in infrastructure
        run: cd infrastructure && flutter analyze

      - name: Run tests in infrastructure
        run: cd infrastructure && flutter test

        
  # build_business:
  #   needs: build_infrastructure
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: subosito/flutter-action@v1.4.0
  #       with:
  #         flutter-version: '1.22.4'

      - name: Install dependencies in business
        run: cd business && flutter pub get

      - name: Generate dart files in business
        run: cd business && flutter pub run build_runner build

      - name: Analyze project source in business
        run: cd business && flutter analyze

      # - name: Run tests
      #   run: cd business && flutter test

        
  build_ui:
    needs: [build_infrastructure]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.4'

      - name: Install dependencies
        run: cd ui && flutter pub get

      - name: Analyze project source
        run: cd ui && flutter analyze

      - name: Build android apk
        run: cd ui && flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: ui/build/app/outputs/apk/release/app-release.apk

      # - name: Run tests
      #   run: cd ui && flutter test

        
